services:
  webserver:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs/server.crt:/etc/nginx/certs/server.crt:ro
      - ./certs/server.key:/etc/nginx/certs/server.key:ro
    ports:
      - 80:80
      - 443:443